### ISSUE TITLE
cli docs on website is not up to date

### ISSUE THREAD

**Issue by skoppe** [wercker/wercker#132]
The --enable-gitignore flag is still on the [wercker-cli docs page](http://devcenter.wercker.com/cli/configuration/options-and-flags.html)

No idea where to change this, else I would have submitted pull request.

**Comment by faiq** [comment]
@skoppe thanks for leaving an issue! Since then we've had a little spring cleaning on our docs here is a link to the commits that fixed what you were talking about

https://github.com/wercker/docs/commit/2ce239f97abd6f42566096daee0a9e261fd52f8e

im closing this issue - but if you have any other documentation issues please feel free to file them on our docs repo https://github.com/wercker/docs

cheers!
