### ISSUE TITLE
Support for Docker Registry v2

### ISSUE THREAD

**Issue by metral** [wercker/wercker#136]
Is there an insight as to when the wercker CLI will bump to using v2 of the Docker Registry instead of v1?

https://github.com/wercker/wercker/blob/8a5b89c4b7bd0837b2c253b12ec64b60a9d2344f/docker/docker.go#L323-L326

**Comment by faiq** [comment]
@metral thanks for your interest in the wercker project! i recently submitted a pull request to support the docker registry 2 protocol- it is currently availble for our beta users. You can also run this feature locally by following the instructions on the readme then doing a #126 

`git checkout -b ferengi` 
`git pul origin ferengi` 
`glide install`
`go build`

Anyways- since this is already supported I'm going to close this. Feel free to reopen!
