### ISSUE TITLE
Use .wercker directory

### ISSUE THREAD

**Issue by chiefy** [wercker/wercker#8]
This is kind of a nitpicky thing, but is there any reason that this project needs to create all the `_` directories in my project root? Any reason it couldn't be transitioned to a `.wercker` directory in the future?

**Comment by termie** [comment]
@chiefy we've laid the groundwork for that (you can use --working-dir right now) and I expect we'd like to make it a .wercker, yes :) thanks for your vote

**Comment by vially** [comment]
I think an even better approach would be to use the [XDG spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) instead of throwing everything under the `~/.wercker` directory.

**Comment by termie** [comment]
@vially i am unclear which XDG_* applies to this folder and what the implications would be, if you'd like to explain further i am happy to listen, it doesn't at first glance feel terribly applicable

**Comment by termie** [comment]
the main issue with this switch for local users is that we currently exclude a bunch of directories from the copy over that, should a user pull a new version and those directories are around would really slow down their builds until they clean then up, i'll look into making some sort of warning or deprecation message i suppose

**Comment by vially** [comment]
@termie Sure, I'll try to expand. 

I think most of the data in the `_` directories can be considered cache data. Therefore it should reside in the `$XDG_CACHE_HOME` directory (which should default to `$HOME/.cache` if the environment variable is not set). 

So instead of having one `.wercker` directory in the root of every project everything should be stored in the user-global `$XDG_CACHE_HOME/wercker` directory. Since everything will now reside in a single user-global directory you'll have to find a way to store and address project specific data under this global directory (e.g.: by using the wercker project ID).

Hope this helps clarify what I meant by using the XDG spec.

**Comment by termie** [comment]
@vially it's an interesting thought and not strictly very difficult to implement, but there are a couple benefits to it being in the local directory (.wercker/latest to get to the results of the last build, for example, will be nice)

**Comment by termie** [comment]
i sort of just hit enter there without ending my thought.

anyway, i reached out to ask how popular XDG usage, if i get any more bites i can look into it sooner

**Comment by vially** [comment]
@termie Awesome, thanks.

Regarding `.wercker/latest` I think that can be worked around by adding some helper sub-commands to the wercker cli tool. For example a `cachedir` sub-command to output the full path to the cache directory for the current project. That way you could cd into that directory easily: `cd $(wercker cachedir)/latest`.

**Comment by markmc** [comment]
Responding to the tweet ... hard to know at a glance what's the right thing in this case, but the XDG base dirs are definitely well used. Here's what I've got on my machine: https://gist.github.com/markmc/105d14263b46108e2435

**Comment by Tonnu** [comment]
Since this was merged in, I'm going to close the issue. Feel free to re-open if you have additional comments.

**Comment by vially** [comment]
So, did you follow the XDG standard or did you choose to ignore it?
