### ISSUE TITLE
wercker-api: not authorized to access this resource (status code: 403) when pulling build

### ISSUE THREAD

**Issue by F21** [wercker/wercker#86]
My wercker account was originally created using my Github login. I then requested a password reset to set a password on the account.

```
$ wercker login
########### Logging into wercker! #############
Username: F21
Password: 
Saving token to:  /home/user/.wercker/token
$ wercker pull F21/getting-started-golang
--> No Docker host specified, checking: unix:///var/run/docker.sock
Fetching build information for application F21/getting-started-golang
Downloading Docker repository for build 56ccdf50ab80e2817300d7d4
ERROR wercker-api: not authorized to access this resource (status code: 403)
FATAL Exiting.
```

Wercker version:

```
Version: 1.0.414
Compiled at: 2016-02-20 08:50:21 +1100 AEDT
Git commit: dec70fb5633937fc85ef409b4c33f67c03d9610c
No new version available

```

**Comment by Tonnu** [comment]
In order to pull builds you need to add the `internal/store-container` as the last step to your wercker.yml. You can find the relevant docs here: http://devcenter.wercker.com/docs/steps/internal-steps.html#store-container.

I do find the 403 status code somewhat misleading though. Will create an issue to see if that can be changed.

**Comment by vladgolubev** [comment]
Hey @Tonnu.
After adding `internal/store-container` as a last step my build started to fail. 
![image](https://cloud.githubusercontent.com/assets/3817380/15040745/9f1fe2fe-12bf-11e6-8467-d6713ba65e99.png)
No other error messages present. What does it mean?
